server:
  port: 9096
spring:
  application:
    name: order-mysql-ms
  boot:
    admin:
        #这个就是注册到SpringBootAdmin服务器的Url
        url: http://localhost:9093
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloud_advance?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
eureka:
  client:
    service-url:
       defaultZone: 'http://eureka-registry-server-peer1:9091/eureka/'