CREATE DATABASE IF NOT EXISTS `cloud_advance` CHARSET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

USE `cloud_advance`;

CREATE TABLE `t_user`(
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) DEFAULT NULL COMMENT '用户名',
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
  balance BIGINT COMMENT '余额',
  status TINYINT DEFAULT 1 COMMENT '状态 1:正常 0:禁用'
)COMMENT '用户表';

CREATE TABLE `t_order`(
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  orderCode VARCHAR(60) DEFAULT NULL COMMENT '订单编号',
  userId BIGINT COMMENT '用户id',
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
  amount BIGINT COMMENT '金额',
  status TINYINT DEFAULT 1 COMMENT '状态 1:正常 0:禁用'
)COMMENT '订单表';

CREATE TABLE `t_zuul_route`(
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  path VARCHAR(100) DEFAULT NULL COMMENT '外部url',
  serviceId VARCHAR(50) DEFAULT NULL COMMENT '服务id',
  url VARCHAR(100) DEFAULT NULL COMMENT '路由的目标url',
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
  status TINYINT DEFAULT 1 COMMENT '状态,1:有效,0:无效'
)COMMENT 'Zuul路由表';