CREATE DATABASE IF NOT EXISTS `cloud_advance` CHARSET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

USE `cloud_advance`;

CREATE TABLE `t_user`(
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) DEFAULT NULL COMMENT '用户名',
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
  balance BIGINT COMMENT '余额',
  status TINYINT DEFAULT 1 COMMENT '状态 1:正常 0:禁用'
)COMMENT '用户表';

CREATE TABLE `t_order`(
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  orderCode VARCHAR(30) DEFAULT NULL COMMENT '订单编号',
  userId BIGINT COMMENT '用户id',
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
  amount BIGINT COMMENT '金额',
  status TINYINT DEFAULT 1 COMMENT '状态 1:正常 0:禁用'
)COMMENT '订单表';